[package]
name = "zed_reason"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/reason.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
