id = "reason"
name = "Reason"
description = "Reason support."
version = "0.0.1"
schema_version = 1
authors = ["Charles Oroko <charles.oroko@outlook.com>"]
repository = "https://github.com/chiq2045/zed-reason"

[language_servers.ocamllsp]
name = "ocamllsp"
languages = ["Reason"]

[grammars.reason]
repository = "https://github.com/reasonml-editor/tree-sitter-reason"
commit = "0226cfecaa2257d56d7c3f364f789cba042e403f"
path = "grammars/reason"
